plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - ConjugateDist.md
  - WorkedExamples.md
  - Metropolis-Hastings.md
  - HypothesisTest.md
